name: SCA scan

on: [push]

jobs:
  scanning:
    name: SCA scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: SnykTest
        if: success() || failure()
        # continue-on-error: true
        run: |
            curl -Lo ./snyk "https://github.com/snyk/snyk/releases/download/v1.1060.0/snyk-linux"
            chmod +x snyk
            ls -lrt
            echo "----------Authenticating Snyk-----------"
            ./snyk auth ${{ secrets.SNYK_TOKEN }}
            echo "----------Snyk Scanning-----------"
            ./snyk test --all-projects -d

      - name: TruffleHog Binary scan
        if: success() || failure()
        id: Binaryscan
        # continue-on-error: true
        run: |
            echo "----------Download Latest TruffleHog Binaries-----------"
            curl -q "https://storage.googleapis.com/thog-releases/trufflehog-scanner/latest/fetch.sh" | bash
            echo "----------Binary Scanning-----------"
            ./trufflehog --fail-verified git ${{ github.event.repository.default_branch }} HEAD 
            
