name: Run Semgrep on Pull Requests

on:
  pull_request_target:
    types: [opened, reopened, synchronize, edited]

permissions:
  pull-requests: write
  contents: read

jobs:
  semgrep:
    name: Semgrep Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Semgrep
        run: |
          python -m pip install --upgrade pip
          pip install semgrep

      - name: Run Semgrep
        run: |
          semgrep --config "auto" --json --output semgrep-output.json

      - name: Read Semgrep output
        id: semgrep-output
        run: |
          cat semgrep-output.json
          echo "semgrep-results=$(cat semgrep-output.json)" >> $GITHUB_ENV

      - name: Post Semgrep results as a PR comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: semgrep-results
          path: semgrep-output.json
