name: "ZAP Baseline Scan"

on:
  schedule:
    - cron:  '0 18 * * 6'

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan Juice Shop preview instance on Heroku
    steps:
      - name: Check out Git repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac #v4.0.0
        with:
          ref: develop
      - name: ZAP Scan
        uses: zaproxy/action-baseline@41aee98ebc7cf2802c3beae4e7d4336413a21e43 # v0.9.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'https://preview.owasp-juice.shop'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a -j'

  zap_scan:
      runs-on: ubuntu-latest
      needs: security
      name: Run DAST scan on the web application
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            ref: master
        - name: ZAP Scan
          uses: zaproxy/action-baseline@v0.12.0
          with:
            docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
            target: 'http://testphp.vulnweb.com/'
            rules_file_name: '.zap/rules.tsv'
            cmd_options: '-a'
